version: "3"
services:
  nginx:
    platform: linux/amd64
    image: nginx:bookworm
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    platform: linux/amd64
    image: blaudio/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    platform: linux/amd64
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    platform: linux/amd64
    ports:
      - "6379:6379"

volumes:
  mongo-db:
